/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package support.translate.parser.backup;

@SuppressWarnings("all")
public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Translator p, int id) {
    super(p, id);
  }

}
