/* Generated By:JJTree: Do not edit this line. .\TranslatorTreeConstants.java */

package support.translate.parser.backup;

@SuppressWarnings("all")
public interface TranslatorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDEFINITION = 2;
  public int JJTDEFINITIONCLASS = 3;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Definition",
    "DefinitionClass",
  };
}
