/*******************************************************************************
 * Copyright 2008, 2009, 2010 Sam Bayless.
 * 
 *     This file is part of Golems.
 * 
 *     Golems is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     Golems is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with Golems. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTDefinition.java */

package support.translate.parser;

@SuppressWarnings("all")
public class ASTDefinition extends SimpleNode {
	private String key;
	private String entry; 
	public void setKey(Token t)
	{
		key = t.image.intern();
	}
	public void setEntry(Token t)
	{
		entry = t == null ? "" : t.image.intern();
	}
	
	public String getKey()
	{
		if(key==null || key.length()<2)
			return "";
		return key.substring(0, key.length()-1).trim();
	}
	
	public String getEntry()
	{
		if(entry == null || entry.length() == 0)
			return null;
		return entry.trim();
	}
	
  public ASTDefinition(int id) {
    super(id);
  }

  public ASTDefinition(Translator p, int id) {
    super(p, id);
  }
  
@Override
public boolean equals(Object obj) {
	if (obj instanceof ASTDefinition)
	{
		if(((ASTDefinition) obj).key.equalsIgnoreCase(key))
		{
			return true;
		}
	}
	return false;
}
@Override
public String toString() {
	return super.toString() + " " + key + ":" + entry;
}

@Override
public NodeType getNodeType() {
	return NodeType.Definition;
}

}
