/*******************************************************************************
 * Copyright 2008, 2009, 2010 Sam Bayless.
 * 
 *     This file is part of Golems.
 * 
 *     Golems is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     Golems is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with Golems. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTDefinitionClass.java */

package support.translate.parser;

@SuppressWarnings("all")
public class ASTDefinitionClass extends SimpleNode {
	private String name;
	private int endLine; 
	public int getEndLine() {
		return endLine;
	}
	public void setLine(int line)
	{
		this.endLine = line;
	}
	public String getName() {
		if(name == null || name.length()<2)
			return "";
		return name.substring(0, name.length()-1).trim();
	}
	public void setName(Token t)
	{
		name = t.image.intern();
	}
  public ASTDefinitionClass(int id) {
    super(id);
  }

  public ASTDefinitionClass(Translator p, int id) {
    super(p, id);
  }
@Override
public NodeType getNodeType() {
	return NodeType.DefinitionClass;
}
@Override
public boolean equals(Object obj) {
	if (obj instanceof ASTDefinitionClass)
	{
		if(((ASTDefinitionClass) obj).name.equalsIgnoreCase(name))
		{
			return true;
		}
	}
	return false;
}
}
