/* Generated By:JJTree&JavaCC: Do not edit this line. TranslatorConstants.java */
package support.translate.parser;

@SuppressWarnings("all")
public interface TranslatorConstants {

  int EOF = 0;
  int CLOSE_CLASS = 7;
  int KEY = 8;
  int CLASS = 9;
  int ENTRY = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "\"}\"",
    "<KEY>",
    "<CLASS>",
    "<ENTRY>",
  };

}
