package com.golemgame.mvc.golems;

public class GolemsClassRepository {

	public static final String BOX_CLASS = "Structure.Box";
	public static final String CYL_CLASS = "Structure.Cylinder";
	public static final String SPHERE_CLASS = "Structure.Sphere";
	public static final String CONE_CLASS = "Structure.Cone";
	public static final String PYRAMID_CLASS = "Structure.Pyramid";
	public static final String CAP_CLASS = "Structure.Capsule";
	public static final String MACHINE_CLASS = "Structure.Machine";
	public static final String MACHINE_SPACE_CLASS = "Structure.Machine.Space";
	public static final String ROCKET_CLASS = "Structure.Rocket";
	public static final String HYDRAULIC_CLASS = "Structure.Hydraulic";
	public static final String HINGE_CLASS = "Structure.Hinge";
//	public static final String BALL_SOCKET_CLASS_OLD = "Structure.BallandSocket";
	public static final String BALL_SOCKET_CLASS = "Structure.BallSocket";
	public static final String AXLE_CLASS = "Structure.Axle";
	public static final String GHOST_BOX_CLASS = "Structure.Ghost.Box";
	public static final String GHOST_CYL_CLASS = "Structure.Ghost.Cylinder";
	public static final String GHOST_PYRAMID_CLASS = "Structure.Ghost.Pyramid";
	public static final String GHOST_CONE_CLASS =  "Structure.Ghost.Cone";
	public static final String GHOST_SPHERE_CLASS = "Structure.Ghost.Sphere";
	public static final String CAMERA_CLASS = "Structure.Camera";
	public static final String WIRE_CLASS = "Wire";
	public static final String WIRE_STORE_CLASS = "Wire.store";
	public static final String WIRE_PORT_CLASS = "Wire.port";
	public static final String BATTERY_CLASS = "Structure.Battery";
	public static final String MODIFIER_CLASS = "Structure.Modifier";
	public static final String DISTANCE_SENSOR_CLASS = "Structure.Sensor.Distance";
	public static final String TOUCH_SENSOR_CLASS = "Structure.Sensor.Touch";
	public static final String OSCILLOSCOPE_CLASS = "Structure.Oscilloscope";
	public static final String INPUT_CLASS = "Structure.Controller";
	public static final String APPEARANCE_CLASS = "Structure.Appearance";
	//public static final String FUNCTION_CLASS = "Function";
	public static final String MOTOR_PROPERTIES_CLASS = "Motor.Properties";
	//	public static final String POLYNOMIAL_FUNCTION_CLASS = "Function.Polynmoial";
	public static final String GENERAL_SENSOR_CLASS = "Structure.Sensor.General";
	public static final String MATERIAL_PROPERTIES_CLASS = "Material";
	public static final String GENERAL_SENSOR_SETTINGS_CLASS = "Sensor.General.Settings";
	public static final String GLUE_DECORATOR_CLASS = "Decorator.Glue";
	public static final String GROUP_MANAGER_CLASS = "Group.Manager";
	public static final String GROUP_CLASS = "Group";
	public static final String MACHINE_SPACE_SETTINGS_CLASS = "Structure.Machine.Space.Settings";
	public static final String PARTICLE_EFFECTS_CLASS = "Effects.Particles";
	public static final String ROCKET_PROPELLANT_CLASS = "Structure.Rocket.Propellant.Properties";
	public static final String PARTICLE_EFFECTS_REPOSITORY_CLASS = "Effect.Particle.Repository";
	public static final String GEAR_CLASS = "Structure.Gear";
	public static final String FUNCTION_REPOSITORY_CLASS = "Function.Repository";
	public static final String COLOR_REPOSITORY_CLASS = "Color.Repository";
	public static final String TUBE_CLASS = "Structure.Tube";
	public static final String FUNCTION_CLASS = "Function";
	public static final String SINE_FUNCTION_CLASS = "Function.Sine";
	public static final String POLYNOMIAL_FUNCTION_CLASS = "Function.Polynomial";
	public static final String KNOTTED_FUNCTION_CLASS = "Function.Knotted";
	public static final String COMBINED_FUNCTION_CLASS = "Function.Combined";
	public static final String FUNCTION_SETTINGS_CLASS = "Function.Settings";
	//public static final String FUNCTION_SETTINGS_CLASS = "Function.Complete";
	public static final String LAYER_REPOSITORY_CLASS = "Layer.Repository";
	public static final String LAYER_CLASS = "Layer";
	public static final String SURFACE_PROPERTIES_CLASS = "Surface.Properties";
	public static final String GRAPPLE_CLASS = "Structure.Grapple";
	public static final String LINE_EFFECTS_CLASS = "Effects.Lines";
	public static final String GRAPPLE_LASER_CLASS = "Structure.Grapple.Laser.Properties";
	public static final String CONTACT_CLASS = "Structure.Contact";
	public static final String SQRT_FUNCTION_CLASS = "Function.Sqrt";
	public static final String COLOR_OUTPUT_DEVICE_CLASS = "Device.Output.Color";
	public static final String GRAPH_OUTPUT_DEVICE_CLASS = "Device.Output.Graph";
	public static final String TEXT_OUTPUT_DEVICE_CLASS = "Device.Output.Text";
	
	public static final String KEY_INPUT_DEVICE_CLASS = "Device.Input.Key";
	public static final String SLIDER_INPUT_DEVICE_CLASS = "Device.Input.Slider";
	public static final String TEXT_INPUT_DEVICE_CLASS = "Device.Input.Text";

}
